### ISSUE TITLE
CUDA memory issues

### ISSUE THREAD

**Issue by genekogan** [yusuketomoto/chainer-fast-neuralstyle#3]
at default parameters, CUDA runs out of memory for me (see below stack trace).

if i change batch size to 1, it works, but I am afraid such a small batch size may not produce good results.

at the moment i don't have CUDNN installed. does this use CUDNN? 

Genes-MacBook-Pro:chainer-fast-neuralstyle gene$ python train.py -s /Users/gene/Learn/style-transfer/interp/PicassoPeriods/data/cubist.jpg -d /Users/gene/Downloads/train2014 -g 0
num traning images: 82783
20695 iterations, 2 epochs
epoch 0
iter 0
Traceback (most recent call last):
  File "train.py", line 106, in <module>
    feature_hat = vgg(y)
  File "/Users/gene/Learn/chainer-fast-neuralstyle/net.py", line 100, in __call__
    y3 = F.relu(self.conv3_3(F.relu(self.conv3_2(F.relu(self.conv3_1(h))))))
  File "/usr/local/lib/python2.7/site-packages/chainer/links/connection/convolution_2d.py", line 77, in __call__
    x, self.W, self.b, self.stride, self.pad, self.use_cudnn)
  File "/usr/local/lib/python2.7/site-packages/chainer/functions/connection/convolution_2d.py", line 298, in convolution_2d
    return func(x, W, b)
  File "/usr/local/lib/python2.7/site-packages/chainer/function.py", line 123, in __call__
    outputs = self.forward(in_data)
  File "/usr/local/lib/python2.7/site-packages/chainer/function.py", line 227, in forward
    return self.forward_gpu(inputs)
  File "/usr/local/lib/python2.7/site-packages/chainer/functions/connection/convolution_2d.py", line 77, in forward_gpu
    y = cuda.cupy.empty((n, out_c, out_h, out_w), dtype=x.dtype)
  File "/usr/local/lib/python2.7/site-packages/cupy/creation/basic.py", line 20, in empty
    return cupy.ndarray(shape, dtype=dtype)
  File "cupy/core/core.pyx", line 87, in cupy.core.core.ndarray.__init__ (cupy/core/core.cpp:4930)
  File "cupy/cuda/memory.pyx", line 275, in cupy.cuda.memory.alloc (cupy/cuda/memory.cpp:5497)
  File "cupy/cuda/memory.pyx", line 414, in cupy.cuda.memory.MemoryPool.malloc (cupy/cuda/memory.cpp:8058)
  File "cupy/cuda/memory.pyx", line 430, in cupy.cuda.memory.MemoryPool.malloc (cupy/cuda/memory.cpp:7984)
  File "cupy/cuda/memory.pyx", line 337, in cupy.cuda.memory.SingleDeviceMemoryPool.malloc (cupy/cuda/memory.cpp:6952)
  File "cupy/cuda/memory.pyx", line 357, in cupy.cuda.memory.SingleDeviceMemoryPool.malloc (cupy/cuda/memory.cpp:6779)
  File "cupy/cuda/memory.pyx", line 255, in cupy.cuda.memory._malloc (cupy/cuda/memory.cpp:5439)
  File "cupy/cuda/memory.pyx", line 256, in cupy.cuda.memory._malloc (cupy/cuda/memory.cpp:5360)
  File "cupy/cuda/memory.pyx", line 31, in cupy.cuda.memory.Memory.__init__ (cupy/cuda/memory.cpp:1534)
  File "cupy/cuda/runtime.pyx", line 180, in cupy.cuda.runtime.malloc (cupy/cuda/runtime.cpp:2950)
  File "cupy/cuda/runtime.pyx", line 110, in cupy.cuda.runtime.check_status (cupy/cuda/runtime.cpp:1865)
cupy.cuda.runtime.CUDARuntimeError: cudaErrorMemoryAllocation: out of memory

**Comment by yusuketomoto** [comment]
Yes. It's hard to train on MacbookPro with batches due to VRAM capacity.
I think buying GPU is the best choice...
There is an another option, In this code, input images are resized to (256,256), you can change image size smaller. But it could also spoil the quality.

If you installed chainer after CuDNN installation, CuDNN should be enabled. Otherwise, CuDNN isn't used.

**Comment by genekogan** [comment]
or maybe using a smaller network than VGG_16 (NIN ImageNet?) would help?  thanks for the tip, will try to find a GPU to use.

**Comment by valentinvieriu** [comment]
@genekogan Try to see if you have a scaled resolution on your mac, and if yes change the resolution to retina and try again. In my case this solved the issue.

**Comment by wadkar** [comment]
I have CuDNN installed and enabled (paths set correctly) but I still get the `out of memory` exception.

I am trying to generate output for an image file that is 2.2mb in size (12px image captured from a smartphone). Any hints in this direction?

**Comment by yusuketomoto** [comment]
@wadkar 
1. Reduce input image resolution
2. Use GPU which has more VRAM
3. Generate by CPU (set option `-g -1`)

**Comment by wadkar** [comment]
@yusuketomoto thanks, using CPU for full resolution and `convert -resize 30% ...` worked for GPU

**Comment by fortunto2** [comment]
Hi, i install Chainer with CUDA on AWS GPU x2 instance
without CuDNN

```
~/chainer-fast-neuralstyle$ python generate.py sample_images/tubingen.jpg -m models/seurat.model -g 0 -o sample_images/output.jpg
/usr/local/lib/python2.7/dist-packages/chainer/cuda.py:87: UserWarning: cuDNN is not enabled.
Please reinstall chainer after you install cudnn
(see https://github.com/pfnet/chainer#installation).
  'cuDNN is not enabled.\n'
Traceback (most recent call last):
  File "generate.py", line 30, in <module>
    y = model(x)
  File "/home/ubuntu/chainer-fast-neuralstyle/net.py", line 61, in __call__
    h = self.r4(h, test=test)
  File "/home/ubuntu/chainer-fast-neuralstyle/net.py", line 20, in __call__
    h = F.relu(self.b1(self.c1(x), test=test))
  File "/usr/local/lib/python2.7/dist-packages/chainer/links/connection/convolution_2d.py", line 82, in __call__
    x, self.W, self.b, self.stride, self.pad, self.use_cudnn)
  File "/usr/local/lib/python2.7/dist-packages/chainer/functions/connection/convolution_2d.py", line 316, in convolution_2d
    return func(x, W, b)
  File "/usr/local/lib/python2.7/dist-packages/chainer/function.py", line 130, in __call__
    outputs = self.forward(in_data)
  File "/usr/local/lib/python2.7/dist-packages/chainer/function.py", line 234, in forward
    return self.forward_gpu(inputs)
  File "/usr/local/lib/python2.7/dist-packages/chainer/functions/connection/convolution_2d.py", line 131, in forward_gpu
    cover_all=self.cover_all)
  File "/usr/local/lib/python2.7/dist-packages/chainer/utils/conv.py", line 45, in im2col_gpu
    col = cuda.cupy.empty((n, c, kh, kw, out_h, out_w), dtype=img.dtype)
  File "/usr/local/lib/python2.7/dist-packages/cupy/creation/basic.py", line 20, in empty
    return cupy.ndarray(shape, dtype=dtype)
  File "cupy/core/core.pyx", line 87, in cupy.core.core.ndarray.__init__ (cupy/core/core.cpp:5019)
  File "cupy/cuda/memory.pyx", line 275, in cupy.cuda.memory.alloc (cupy/cuda/memory.cpp:5517)
  File "cupy/cuda/memory.pyx", line 414, in cupy.cuda.memory.MemoryPool.malloc (cupy/cuda/memory.cpp:8078)
  File "cupy/cuda/memory.pyx", line 430, in cupy.cuda.memory.MemoryPool.malloc (cupy/cuda/memory.cpp:8004)
  File "cupy/cuda/memory.pyx", line 337, in cupy.cuda.memory.SingleDeviceMemoryPool.malloc (cupy/cuda/memory.cpp:6972)
  File "cupy/cuda/memory.pyx", line 357, in cupy.cuda.memory.SingleDeviceMemoryPool.malloc (cupy/cuda/memory.cpp:6799)
  File "cupy/cuda/memory.pyx", line 255, in cupy.cuda.memory._malloc (cupy/cuda/memory.cpp:5459)
  File "cupy/cuda/memory.pyx", line 256, in cupy.cuda.memory._malloc (cupy/cuda/memory.cpp:5380)
  File "cupy/cuda/memory.pyx", line 31, in cupy.cuda.memory.Memory.__init__ (cupy/cuda/memory.cpp:1542)
  File "cupy/cuda/runtime.pyx", line 181, in cupy.cuda.runtime.malloc (cupy/cuda/runtime.cpp:3065)
  File "cupy/cuda/runtime.pyx", line 111, in cupy.cuda.runtime.check_status (cupy/cuda/runtime.cpp:1980)
cupy.cuda.runtime.CUDARuntimeError: cudaErrorMemoryAllocation: out of memory


```

**Comment by ttoinou** [comment]
@fortunto2  : The error might be that... you don't have enough memory. I don't understand your point.

**Comment by fortunto2** [comment]
max value 1015MiB
in interval 1sec
nvidia-smi -l 1 

![2016-08-05 00-52-20](https://cloud.githubusercontent.com/assets/1236751/17416290/454db37c-5aaf-11e6-857a-aeaa3414f15f.png)

**Comment by ttoinou** [comment]
Could you try with smaller image sizes in order to see the last stats before it crashes ?

**Comment by fortunto2** [comment]
yes work with small size
gpu 0.48 sec
cpu 0.59 sec
it's normal?
for 218*230image
https://pp.vk.me/c614825/v614825550/1bdc2/-GJFkroeHiQ.jpg

**Comment by ttoinou** [comment]
Well it's slow for the GPU but it might be because of the model loading not the generation of the image. By stats I was talking about the memory :) .
Resize the image bigger and bigger to see the memory consumption and when it breaks.
( if it's written 1000MB and has ran out of memory doesn't mean that he was only trying to allocate 1000 MB but much more and you can't see it in the stats. I think 1000 MB is just the memory he succeeded in allocating )
